##
## EPITECH PROJECT, 2021
## makefile
## File description:
## makefile
##

SRC			=	DoOp.hs

NAME	=	doop

CC	= ghci

all:	$(NAME)

$(NAME):	$(NAME)
			$(CC) $(SRC)

clean:
	rm -f $(OBJ)

fclean:	clean
	rm -f $(NAME)

re:		fclean all

.PHONY:	clean all fclean re